# R for travis: see documentation at https://docs.travis-ci.com/user/languages/r

language: r

sudo: required

dist: trusty

warnings_are_errors: true

r:
  - release
  - devel

r_build_args: --no-build-vignettes

os:
  - linux
  - osx

matrix:
  exclude:
    - os: osx
      r: devel

env:
  global:
    - _R_CHECK_FORCE_SUGGESTS_=FALSE

apt_packages:
  - curl
  - qpdf
  - coinor-libcgl-dev
  - coinor-libclp-dev
  - coinor-libcoinutils-dev
  - coinor-libosi-dev
  - coinor-libsymphony-dev
  - coinor-libsymphony-doc
  - coinor-libsymphony3

before_install:
  - echo "TRAVIS_OS_NAME = $TRAVIS_OS_NAME"
  - echo "options(repos = c(CRAN='http://cran.rstudio.com'))" > ~/.Rprofile
  - if [ "$TRAVIS_OS_NAME" == "linux" ]; then sudo apt-get --yes --force-yes update -qq; fi;
  - if [ "$TRAVIS_OS_NAME" == "linux" ]; then sudo apt-get install -y; fi;
  - if [ "$TRAVIS_OS_NAME" == "linux" ]; then sudo add-apt-repository ppa:ubuntugis/ubuntugis-unstable; fi;
  - if [ "$TRAVIS_OS_NAME" == "linux" ]; then sudo add-get update; fi;
  - if [ "$TRAVIS_OS_NAME" == "linux" ]; then sudo add-get install libudunits2-dev libgdal-dev libgeos-dev libproj-dev; fi;
  - if [ "$TRAVIS_OS_NAME" == "linux" ]; then Rscript -e "install.packages(c('sp', 'devtools'))"; fi;
  - if [ "$TRAVIS_OS_NAME" == "osx" ]; then brew install Caskroom/cask/xquartz; fi;
  - if [ "$TRAVIS_OS_NAME" == "osx" ]; then brew install ghostscript; fi;
  - if [ "$TRAVIS_OS_NAME" == "osx" ]; then Rscript -e "setRepositories(ind=1:2);install.packages(c('rgdal','rgeos','RandomFieldsUtils','RandomFields'))"; fi;
  - if [ "$TRAVIS_OS_NAME" == "osx" ]; then sudo tlmgr update --self; fi;

before_script:
  - Rscript -e "source('http://bioconductor.org/biocLite.R');biocLite('lpsymphony')"

r_packages:
  - covr
  - rmarkdown
  - testthat

after_success:
  - Rscript -e 'covr::codecov()'

notifications:
  email:
    on_success: change
    on_failure: change
